name: Package Update Source

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  test-build:
    name: Test Kernel Module Build (in Docker) - Ubuntu ${{ matrix.ubuntu_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: ["25.04", "25.10", "26.04"]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Replace Ubuntu version in Dockerfile
        run: sed -i "s/^FROM ubuntu:.*/FROM ubuntu:${{ matrix.ubuntu_version }}/" Dockerfile

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          tags: test:${{ github.sha }}-ubuntu${{ matrix.ubuntu_version }}
          push: false

  package-and-deploy:
    name: Build, Sign, and Deploy APT Repository
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v7

      - name: Install Debian Packaging Tools and public key
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev apt-utils sq pandoc
          echo "${{ secrets.GPG_PUBLIC_KEY }}" > public.key
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key

      - name: Create Debian Directory Layout
        run: |
          ./scripts/build_package.sh

      - name: Convert Markdown to HTML
        run: |
          mkdir -p public

          find . -name "*.md" -not -path "./public/*" -not -path "./.github/*" | while read -r file; do
            rel_path="${file#./}"
            out_path="public/${rel_path%.md}.html"
            mkdir -p "$(dirname "$out_path")"
            sed -i 's/\.md/\.html/g' "$file"
            pandoc "$file" -s -o "$out_path" --metadata title="$(basename "${file%.md}")"
          done
          mv ./public/README.html ./public/index.html
          mv repo-dist ./public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
